'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace gr.gsis.www1
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="RgWsPublic2Service_SOAP_HTTP", [Namespace]:="http://rgwspublic2/RgWsPublic2Service")>  _
    Partial Public Class RgWsPublic2Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private rgWsPublic2VersionInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private rgWsPublic2AfmMethodOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12
            Me.Url = Global.EstiaSYS.Settings.Default.EstiaSYS_gr_gsis_www1_RgWsPublic2Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event rgWsPublic2VersionInfoCompleted As rgWsPublic2VersionInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event rgWsPublic2AfmMethodCompleted As rgWsPublic2AfmMethodCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rgwspublic2/RgWsPublic2Service:rgWsPublic2VersionInfo", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function rgWsPublic2VersionInfo(<System.Xml.Serialization.XmlElementAttribute("rgWsPublic2VersionInfo", [Namespace]:="http://rgwspublic2/RgWsPublic2Service")> ByVal rgWsPublic2VersionInfo1 As rgWsPublic2VersionInfoRequestType) As <System.Xml.Serialization.XmlElementAttribute("rgWsPublic2VersionInfoResponse", [Namespace]:="http://rgwspublic2/RgWsPublic2Service")> rgWsPublic2VersionInfoResponseType
            Dim results() As Object = Me.Invoke("rgWsPublic2VersionInfo", New Object() {rgWsPublic2VersionInfo1})
            Return CType(results(0),rgWsPublic2VersionInfoResponseType)
        End Function
        
        '''<remarks/>
        Public Overloads Sub rgWsPublic2VersionInfoAsync(ByVal rgWsPublic2VersionInfo1 As rgWsPublic2VersionInfoRequestType)
            Me.rgWsPublic2VersionInfoAsync(rgWsPublic2VersionInfo1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub rgWsPublic2VersionInfoAsync(ByVal rgWsPublic2VersionInfo1 As rgWsPublic2VersionInfoRequestType, ByVal userState As Object)
            If (Me.rgWsPublic2VersionInfoOperationCompleted Is Nothing) Then
                Me.rgWsPublic2VersionInfoOperationCompleted = AddressOf Me.OnrgWsPublic2VersionInfoOperationCompleted
            End If
            Me.InvokeAsync("rgWsPublic2VersionInfo", New Object() {rgWsPublic2VersionInfo1}, Me.rgWsPublic2VersionInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnrgWsPublic2VersionInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.rgWsPublic2VersionInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent rgWsPublic2VersionInfoCompleted(Me, New rgWsPublic2VersionInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rgwspublic2/RgWsPublic2Service:rgWsPublic2AfmMethod", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function rgWsPublic2AfmMethod(<System.Xml.Serialization.XmlElementAttribute("rgWsPublic2AfmMethod", [Namespace]:="http://rgwspublic2/RgWsPublic2Service")> ByVal rgWsPublic2AfmMethod1 As rgWsPublic2AfmMethodRequestType) As <System.Xml.Serialization.XmlElementAttribute("rgWsPublic2AfmMethodResponse", [Namespace]:="http://rgwspublic2/RgWsPublic2Service")> rgWsPublic2AfmMethodResponseType
            Dim results() As Object = Me.Invoke("rgWsPublic2AfmMethod", New Object() {rgWsPublic2AfmMethod1})
            Return CType(results(0),rgWsPublic2AfmMethodResponseType)
        End Function
        
        '''<remarks/>
        Public Overloads Sub rgWsPublic2AfmMethodAsync(ByVal rgWsPublic2AfmMethod1 As rgWsPublic2AfmMethodRequestType)
            Me.rgWsPublic2AfmMethodAsync(rgWsPublic2AfmMethod1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub rgWsPublic2AfmMethodAsync(ByVal rgWsPublic2AfmMethod1 As rgWsPublic2AfmMethodRequestType, ByVal userState As Object)
            If (Me.rgWsPublic2AfmMethodOperationCompleted Is Nothing) Then
                Me.rgWsPublic2AfmMethodOperationCompleted = AddressOf Me.OnrgWsPublic2AfmMethodOperationCompleted
            End If
            Me.InvokeAsync("rgWsPublic2AfmMethod", New Object() {rgWsPublic2AfmMethod1}, Me.rgWsPublic2AfmMethodOperationCompleted, userState)
        End Sub
        
        Private Sub OnrgWsPublic2AfmMethodOperationCompleted(ByVal arg As Object)
            If (Not (Me.rgWsPublic2AfmMethodCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent rgWsPublic2AfmMethodCompleted(Me, New rgWsPublic2AfmMethodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rgwspublic2/RgWsPublic2Service")>  _
    Partial Public Class rgWsPublic2VersionInfoRequestType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rgwspublic2/RgWsPublic2")>  _
    Partial Public Class rg_ws_public2_firm_act_rtType
        
        Private firm_act_codeField As System.Nullable(Of Decimal)
        
        Private firm_act_codeFieldSpecified As Boolean
        
        Private firm_act_descrField As String
        
        Private firm_act_kindField As String
        
        Private firm_act_kind_descrField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property firm_act_code() As System.Nullable(Of Decimal)
            Get
                Return Me.firm_act_codeField
            End Get
            Set
                Me.firm_act_codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property firm_act_codeSpecified() As Boolean
            Get
                Return Me.firm_act_codeFieldSpecified
            End Get
            Set
                Me.firm_act_codeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property firm_act_descr() As String
            Get
                Return Me.firm_act_descrField
            End Get
            Set
                Me.firm_act_descrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property firm_act_kind() As String
            Get
                Return Me.firm_act_kindField
            End Get
            Set
                Me.firm_act_kindField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property firm_act_kind_descr() As String
            Get
                Return Me.firm_act_kind_descrField
            End Get
            Set
                Me.firm_act_kind_descrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rgwspublic2/RgWsPublic2")>  _
    Partial Public Class rg_ws_public2_basic_rtType
        
        Private afmField As String
        
        Private doyField As String
        
        Private doy_descrField As String
        
        Private i_ni_flag_descrField As String
        
        Private deactivation_flagField As String
        
        Private deactivation_flag_descrField As String
        
        Private firm_flag_descrField As String
        
        Private onomasiaField As String
        
        Private commer_titleField As String
        
        Private legal_status_descrField As String
        
        Private postal_addressField As String
        
        Private postal_address_noField As String
        
        Private postal_zip_codeField As String
        
        Private postal_area_descriptionField As String
        
        Private regist_dateField As System.Nullable(Of Date)
        
        Private regist_dateFieldSpecified As Boolean
        
        Private stop_dateField As System.Nullable(Of Date)
        
        Private stop_dateFieldSpecified As Boolean
        
        Private normal_vat_system_flagField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property afm() As String
            Get
                Return Me.afmField
            End Get
            Set
                Me.afmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property doy() As String
            Get
                Return Me.doyField
            End Get
            Set
                Me.doyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property doy_descr() As String
            Get
                Return Me.doy_descrField
            End Get
            Set
                Me.doy_descrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property i_ni_flag_descr() As String
            Get
                Return Me.i_ni_flag_descrField
            End Get
            Set
                Me.i_ni_flag_descrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property deactivation_flag() As String
            Get
                Return Me.deactivation_flagField
            End Get
            Set
                Me.deactivation_flagField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property deactivation_flag_descr() As String
            Get
                Return Me.deactivation_flag_descrField
            End Get
            Set
                Me.deactivation_flag_descrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property firm_flag_descr() As String
            Get
                Return Me.firm_flag_descrField
            End Get
            Set
                Me.firm_flag_descrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property onomasia() As String
            Get
                Return Me.onomasiaField
            End Get
            Set
                Me.onomasiaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property commer_title() As String
            Get
                Return Me.commer_titleField
            End Get
            Set
                Me.commer_titleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property legal_status_descr() As String
            Get
                Return Me.legal_status_descrField
            End Get
            Set
                Me.legal_status_descrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property postal_address() As String
            Get
                Return Me.postal_addressField
            End Get
            Set
                Me.postal_addressField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property postal_address_no() As String
            Get
                Return Me.postal_address_noField
            End Get
            Set
                Me.postal_address_noField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property postal_zip_code() As String
            Get
                Return Me.postal_zip_codeField
            End Get
            Set
                Me.postal_zip_codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property postal_area_description() As String
            Get
                Return Me.postal_area_descriptionField
            End Get
            Set
                Me.postal_area_descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", IsNullable:=true)>  _
        Public Property regist_date() As System.Nullable(Of Date)
            Get
                Return Me.regist_dateField
            End Get
            Set
                Me.regist_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property regist_dateSpecified() As Boolean
            Get
                Return Me.regist_dateFieldSpecified
            End Get
            Set
                Me.regist_dateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", IsNullable:=true)>  _
        Public Property stop_date() As System.Nullable(Of Date)
            Get
                Return Me.stop_dateField
            End Get
            Set
                Me.stop_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property stop_dateSpecified() As Boolean
            Get
                Return Me.stop_dateFieldSpecified
            End Get
            Set
                Me.stop_dateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property normal_vat_system_flag() As String
            Get
                Return Me.normal_vat_system_flagField
            End Get
            Set
                Me.normal_vat_system_flagField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rgwspublic2/RgWsPublic2")>  _
    Partial Public Class rg_ws_public2_afm_called_by_rtType
        
        Private token_usernameField As String
        
        Private token_afmField As String
        
        Private token_afm_fullnameField As String
        
        Private afm_called_byField As String
        
        Private afm_called_by_fullnameField As String
        
        Private as_on_dateField As System.Nullable(Of Date)
        
        Private as_on_dateFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property token_username() As String
            Get
                Return Me.token_usernameField
            End Get
            Set
                Me.token_usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property token_afm() As String
            Get
                Return Me.token_afmField
            End Get
            Set
                Me.token_afmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property token_afm_fullname() As String
            Get
                Return Me.token_afm_fullnameField
            End Get
            Set
                Me.token_afm_fullnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property afm_called_by() As String
            Get
                Return Me.afm_called_byField
            End Get
            Set
                Me.afm_called_byField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property afm_called_by_fullname() As String
            Get
                Return Me.afm_called_by_fullnameField
            End Get
            Set
                Me.afm_called_by_fullnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", IsNullable:=true)>  _
        Public Property as_on_date() As System.Nullable(Of Date)
            Get
                Return Me.as_on_dateField
            End Get
            Set
                Me.as_on_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property as_on_dateSpecified() As Boolean
            Get
                Return Me.as_on_dateFieldSpecified
            End Get
            Set
                Me.as_on_dateFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rgwspublic2/RgWsPublic2")>  _
    Partial Public Class gen_ws_error_rtType
        
        Private error_codeField As String
        
        Private error_descrField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property error_code() As String
            Get
                Return Me.error_codeField
            End Get
            Set
                Me.error_codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property error_descr() As String
            Get
                Return Me.error_descrField
            End Get
            Set
                Me.error_descrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rgwspublic2/RgWsPublic2")>  _
    Partial Public Class rg_ws_public2_result_rtType
        
        Private call_seq_idField As System.Nullable(Of Decimal)
        
        Private call_seq_idFieldSpecified As Boolean
        
        Private error_recField As gen_ws_error_rtType
        
        Private afm_called_by_recField As rg_ws_public2_afm_called_by_rtType
        
        Private basic_recField As rg_ws_public2_basic_rtType
        
        Private firm_act_tabField() As rg_ws_public2_firm_act_rtType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property call_seq_id() As System.Nullable(Of Decimal)
            Get
                Return Me.call_seq_idField
            End Get
            Set
                Me.call_seq_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property call_seq_idSpecified() As Boolean
            Get
                Return Me.call_seq_idFieldSpecified
            End Get
            Set
                Me.call_seq_idFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property error_rec() As gen_ws_error_rtType
            Get
                Return Me.error_recField
            End Get
            Set
                Me.error_recField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property afm_called_by_rec() As rg_ws_public2_afm_called_by_rtType
            Get
                Return Me.afm_called_by_recField
            End Get
            Set
                Me.afm_called_by_recField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property basic_rec() As rg_ws_public2_basic_rtType
            Get
                Return Me.basic_recField
            End Get
            Set
                Me.basic_recField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable:=false)>  _
        Public Property firm_act_tab() As rg_ws_public2_firm_act_rtType()
            Get
                Return Me.firm_act_tabField
            End Get
            Set
                Me.firm_act_tabField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rgwspublic2/RgWsPublic2Service")>  _
    Partial Public Class rgWsPublic2AfmMethodResponseType
        
        Private resultField As rgWsPublic2AfmMethodResponseTypeResult
        
        '''<remarks/>
        Public Property result() As rgWsPublic2AfmMethodResponseTypeResult
            Get
                Return Me.resultField
            End Get
            Set
                Me.resultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://rgwspublic2/RgWsPublic2Service")>  _
    Partial Public Class rgWsPublic2AfmMethodResponseTypeResult
        
        Private rg_ws_public2_result_rtTypeField As rg_ws_public2_result_rtType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://rgwspublic2/RgWsPublic2")>  _
        Public Property rg_ws_public2_result_rtType() As rg_ws_public2_result_rtType
            Get
                Return Me.rg_ws_public2_result_rtTypeField
            End Get
            Set
                Me.rg_ws_public2_result_rtTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rgwspublic2/RgWsPublic2")>  _
    Partial Public Class rg_ws_public2_input_rtType
        
        Private afm_called_byField As String
        
        Private afm_called_forField As String
        
        Private as_on_dateField As System.Nullable(Of Date)
        
        Private as_on_dateFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property afm_called_by() As String
            Get
                Return Me.afm_called_byField
            End Get
            Set
                Me.afm_called_byField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property afm_called_for() As String
            Get
                Return Me.afm_called_forField
            End Get
            Set
                Me.afm_called_forField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", IsNullable:=true)>  _
        Public Property as_on_date() As System.Nullable(Of Date)
            Get
                Return Me.as_on_dateField
            End Get
            Set
                Me.as_on_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property as_on_dateSpecified() As Boolean
            Get
                Return Me.as_on_dateFieldSpecified
            End Get
            Set
                Me.as_on_dateFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rgwspublic2/RgWsPublic2Service")>  _
    Partial Public Class rgWsPublic2AfmMethodRequestType
        
        Private iNPUT_RECField As rg_ws_public2_input_rtType
        
        '''<remarks/>
        Public Property INPUT_REC() As rg_ws_public2_input_rtType
            Get
                Return Me.iNPUT_RECField
            End Get
            Set
                Me.iNPUT_RECField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rgwspublic2/RgWsPublic2Service")>  _
    Partial Public Class rgWsPublic2VersionInfoResponseType
        
        Private resultField As String
        
        '''<remarks/>
        Public Property result() As String
            Get
                Return Me.resultField
            End Get
            Set
                Me.resultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub rgWsPublic2VersionInfoCompletedEventHandler(ByVal sender As Object, ByVal e As rgWsPublic2VersionInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class rgWsPublic2VersionInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As rgWsPublic2VersionInfoResponseType
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),rgWsPublic2VersionInfoResponseType)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub rgWsPublic2AfmMethodCompletedEventHandler(ByVal sender As Object, ByVal e As rgWsPublic2AfmMethodCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class rgWsPublic2AfmMethodCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As rgWsPublic2AfmMethodResponseType
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),rgWsPublic2AfmMethodResponseType)
            End Get
        End Property
    End Class
End Namespace
